version: '3.7'

services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hapi-test-api
    environment:
      - PORT
      - NODE_ENV_PROTECTED
    volumes:
      - ./logs:/app/logs
      - ./:/app/
    restart: always
    networks:
      - internal_network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db

  db:
    image: docker.io/bitnami/postgresql:13.3.0
    container_name: hapi-db-api
    volumes:
      - '.:/app'
    restart: always
    networks:
      - internal_network
    ports:
      - 5432:5432
    environment:
          - POSTGRESQL_USERNAME=postgres12
          - POSTGRESQL_PASSWORD=postgres
          - POSTGRESQL_DATABASE=my_database      

  pg-admin:
    image: dpage/pgadmin4
    container_name: hapi-pg-admin
    restart: always
    logging:
      driver: none
    networks:
      - internal_network
    ports:
      - 5001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  internal_network:
    driver: bridge
