version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal_network
    ports:
      - ${PORT-4000}:${PORT-4000}
    volumes:
      - ./logs:/app/logs
      - ./:/app/
    restart: unless-stopped
    environment:
      NODE_ENV_PROTECTED: ${NODE_ENV_PROTECTED}
    depends_on:
      - db
  db:
    image: docker.io/bitnami/postgresql:13.3.0
    volumes:
      - '.:/app'
    restart: always
    networks:
      - internal_network
    ports:
      - 5432:5432
    environment:
          - POSTGRESQL_USERNAME=postgres12
          - POSTGRESQL_PASSWORD=postgres
          - POSTGRESQL_DATABASE=my_database      
networks:
  internal_network:
      driver: bridge